[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_byte_store = "EPHfyiTc9VqV9Cpoyb7HGfVjfAvxms58pARnuq233FhN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nullfinder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
